### PR TITLE
Update custom_stylesheet.md

### PR DESCRIPTION
**Pull request by lahtinen**
Hi
There was an error in document, please update.

### CODE REVIEW

**Comment by RyanMPierson** [comment]
The Gantry template would work with gantry-custom.css, but a Gantry-based template named, for example, Myriad would generally go with myriad-custom.css.  This is why we went with [Template] as a placeholder for the proper template name.

**Comment by lahtinen** [comment]
Thanks, but i just tried and it wont work with template name on filename.

**Comment by RyanMPierson** [comment]
This can be a bit confusing. It's not necessarily the proper name of the template, but rather than folder name the template is in. For example, RocketTheme templates usually have folder names that start with rt_ as in rt_myriad. Have you tried matching to the folder name?

**Comment by lahtinen** [comment]
Thanks, that was my mistake. There was an image paths on css rules that was not working. Sorry for inconvenience!

**Pull request closed without merging**
